dist: bionic
language: python
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      language: shell
    - os: linux
      python: 3.7
install:
  - pip3 install cmdstanpy
script: python3 debug.py
notifications:
  email:
    on_success: never
    on_failure: change
