name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # - uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.7
    #     bundler-cache: true
    - run: which make
    - run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: which make
    - run: echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: which make
    - if: ${{ startsWith(matrix.os, 'windows') }}
      run: ls C:\msys64\usr\bin\
    - run: mingw32-make
    # - run: bundle exec ruby ext/cmdstan/extconf.rb
    # - run: bundle exec rake test
